trigger: none

#schedules:
#- cron: "10 * * * *"
#  displayName: Déclenchement quotidien
#  branches:
#    include:
#      - master  

pool: 
  PoolAgentSelf

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Local-K8s-Cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/deployment.yaml'
