trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: docker-hub-connexion

# Commande Docker pour scanner l'image avec Trivy
- script: |
    docker run --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(System.DefaultWorkingDirectory):/root/.cache/ \
      aquasec/trivy:latest image \
      --output /root/.cache/trivy-report.sarif \
      aminelemsi/app-examavocat:latest
  displayName: 'Scan Docker image with Trivy'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/trivy-report.sarif'
    artifactName: 'trivy-reports'
  displayName: 'Publish Trivy scan results'