trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    # Construire l'image Docker avec un tag
    docker build -t aminelemsi/app-examavocat:latest .
  displayName: 'Build Docker image'
- script: |
    docker run --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(System.DefaultWorkingDirectory):/root/.cache/ \
      aquasec/trivy:latest image --format sarif --output /root/.cache/trivy-report.sarif aminelemsi/app-examavocat:latest
  displayName: 'Run Trivy scan'

- task: Docker@2
  inputs:
    command: 'push'
    containerRegistry: 'docker-hub-connexion'
    repository: 'aminelemsi/app-examavocat'
    tags: 'latest'
  displayName: 'Push Docker image to container registry'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/trivy-report.sarif'
    artifactName: 'trivy-reports'
  displayName: 'Publish Trivy scan results'