trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    # Construire l'image Docker avec un tag
    docker build -t aminelemsi/app-examavocat:latest .
  displayName: 'Build Docker image'

- task: Docker@2
  inputs:
    command: 'push'
    containerRegistry: 'docker-hub-connexion'
    repository: 'aminelemsi/app-examavocat'
    tags: 'latest'
  displayName: 'Push Docker image to container registry'


# Commande Docker pour scanner l'image avec Trivy
- script: |
    docker run --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(System.DefaultWorkingDirectory):/root/.cache/ \
      aquasec/trivy:db image \
      --format sarif \
      --output trivy-results.sarif \
      aminelemsi/app-examavocat:latest
  displayName: 'Scan Docker image with Trivy'

# Publier les résultats du scan Trivy en tant qu'artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/trivy-results.sarif'
    artifactName: 'TrivyScanResults'
    publishLocation: 'pipeline'
  displayName: 'Publish Trivy scan results as pipeline artifact'