apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-examavocat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examavocat
  template:
    metadata:
      labels:
        app: examavocat
    spec:
      containers:
      - name: app-examavocat
        image: aminelemsi/app-examavocat:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-examavocat-service
spec:
  type: NodePort
  selector:
    app: examavocat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30000
